# Part 1

## NumPy Arrays

the main difference between Arrays and matrices is that arrays are one dimenstiona 

In [1]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [2]:
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3])

#### how to create a matrix ? I.e. 2d array

In [4]:
mat= [[1,2,3],[4,5,6],[7,8,9]] #this is a List (list inside a list)
mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(mat) #here i have changed it from a list into a 2d array (matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Arange, Zeros, Ones, Linspace, Identity 

#### to create an array (let python create one for you)

In [6]:
np.arange(0,10,5) #start,end,steps size

array([0, 5])

In [7]:
np.zeros((5,5))  #rows,columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.linspace(0,10,5)  #start, stop, number of steps

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
print(np.arange(0,10,5)) #start,end,steps size
print(np.linspace(0,10,5)) #start, stop, number of steps

[0 5]
[ 0.   2.5  5.   7.5 10. ]


In [11]:
np.eye(5) #diaognal =1 other values =0

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random matrix

In [12]:
np.random.rand(3) #rand = 1d array of random number 
                  #   uniformly distrubuted between 0 and 1 

array([0.91910918, 0.21810892, 0.79361848])

In [13]:
np.random.rand(3,5) #2d

array([[0.43108093, 0.89780385, 0.39456129, 0.92310955, 0.87103048],
       [0.06860646, 0.93438168, 0.30125218, 0.15163801, 0.40889794],
       [0.81666873, 0.12885178, 0.64541165, 0.95004254, 0.5542751 ]])

In [14]:
np.random.randn(4,2) # not necessarly 0 to 1 

array([[-0.15422899, -0.29918646],
       [ 1.38674505,  0.85955636],
       [ 0.97074179,  0.38265471],
       [ 1.6443469 ,  0.18448215]])

In [15]:
np.random.randint(5,100,10)  #give us random number between 5 to 99, 
                             #the third is for how many numbers u want

array([29, 44, 32, 45, 28, 95, 30, 17,  8, 89])

### Array Attributes and Methods

In [67]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
ranarr = np.random.randint(0,50,10)
ranarr

array([26, 10, 33, 12, 44, 24, 44, 42, 30, 15])

#### ReShape the array

In [69]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

#### min and max and location

In [19]:
ranarr.max()

44

In [20]:
ranarr.min()

10

In [21]:
ranarr.argmax() #index location of that value

4

In [22]:
ranarr.argmin() #location of index of min value

1

#### shape of the array

In [23]:
arr.shape   #shape of your array

(25,)

In [24]:
qq = arr.reshape(5,5)
qq.shape

(5, 5)

#### Data type

In [25]:
arr.dtype #its a 32 pit integer

dtype('int32')


# Part 2

#### slicing and indexing

In [26]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr[8]   #to find the 8th value

8

In [28]:
arr[0:5]  #slicing new boastin 

array([0, 1, 2, 3, 4])

In [29]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [30]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [31]:
arr[0:5] = 100  #change these values to 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [32]:
arr = np.arange(1,11)

In [33]:
slice_of_arr = arr[0:6]
slice_of_arr

array([1, 2, 3, 4, 5, 6])

In [34]:
slice_of_arr [:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [35]:
arr  #this is changed now, this is how python work

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [36]:
arr_copy = arr.copy()

In [37]:
arr_copy[:] = 100

In [38]:
arr_copy #by using the copy methon ur only 
         #changing the new array not the old one

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [39]:
arr

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

### 2d array: matrix 

In [40]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [41]:
arr_2d[2][1]  #double braccet notation for indexing

40

In [42]:
arr_2d[2,1]  #single brracet comma notation (matlab notation) :D for indexing

40

In [43]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [44]:
arr_2d[1:,1:] #

array([[25, 30],
       [40, 45]])

### practice for me

In [45]:
sw = np.arange(30)
sw

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [46]:
sq = sw.reshape(5,6)
sq

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [47]:
sq[:2,3:]

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [48]:
#you can also do
qs = np.arange(30).reshape(5,6)
qs
#easy right?

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [49]:
qs[3:4,:2]

array([[18, 19]])

### conditional selection/slicing

In [50]:
arr= np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
t_or_f = arr >15

In [52]:
arr[t_or_f]

array([16, 17, 18, 19, 20, 21, 22, 23, 24])

In [53]:
arr[arr>15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24])

# Part 3

## NumPy Operation
### simple operation to array

In [54]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [56]:
arr * 2* arr

array([  0,   2,   8,  18,  32,  50,  72,  98, 128, 162, 200])

In [57]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [58]:
arr / arr  #warning below is because 0/0 is not valid,
           #this is a warning not an error

D:\anaconda\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

### universal array function

In [59]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [60]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [61]:
np.max(arr)

10

In [62]:
arr.max() #same as line above

10

In [63]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [64]:
#all universal array functionscan be found in the note provided for this part